### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [6871/6871.github.io#1]
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/BVBUKL

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by 6871** [comment]
Sorry for the delayed response, I got the population figures from the following UN location:

- https://www.unfpa.org/data/world-population-dashboard
- https://www.unfpa.org/sites/default/files/SWOP-Data-2019.xlsx (see tab Demographic_2019)

I'd have thought your best bet would be to extract direct from there.
